### PR TITLE
Lab05 submission for Dan Luo

### PR DESCRIPTION
**Pull request by pichumy**
Added animation for SwordWithHilt

### CODE REVIEW

**Comment by mliou** [comment]
I can't merge the old changes for lab04, it causes a merge conflict. Besides, lab04 has already been graded and cannot be changed. Please make a new pull request with only the lab05 changes.

**Comment by pichumy** [comment]
sorry for the late response, not entirely sure what you want me to do?

**Comment by mliou** [comment]
Include only the "Added animation for lab05" commit in your pull request.

**Comment by pichumy** [comment]
How do I get rid of the other commit?

**Comment by mliou** [comment]
I think it would be easiest if you just manually undid those changes. It's only a couple of files.

**Pull request merged**
